# Generated by Django 2.2 on 2019-05-13 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
            ],
            options={
                'verbose_name': 'Unidade',
                'verbose_name_plural': 'Unidades',
            },
        ),
        migrations.CreateModel(
            name='ClassRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Dia do registro')),
                ('start_class', models.TimeField(blank=True, null=True, verbose_name='Início do treinamento')),
                ('end_class', models.TimeField(blank=True, null=True, verbose_name='Termino do treinamento')),
                ('conclude', models.BooleanField(default=False, verbose_name='Registro Concluido')),
            ],
            options={
                'verbose_name': 'Registro de Treino',
                'verbose_name_plural': 'Registros de Treino',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, verbose_name='Nome do Local')),
                ('address', models.CharField(max_length=100, verbose_name='Endereço')),
            ],
            options={
                'verbose_name': 'Local',
                'verbose_name_plural': 'Locais',
            },
        ),
        migrations.CreateModel(
            name='PreparationClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75, verbose_name='Título do treinamento')),
                ('date', models.DateField(verbose_name='Dia do treinamento')),
                ('time', models.TimeField(verbose_name='Hora do treinamento')),
                ('duration', models.IntegerField(help_text='Nota: quantidade inserida em minutos', verbose_name='Duração do treinamento')),
                ('description', models.TextField(max_length=140)),
            ],
            options={
                'verbose_name': 'Treinamento',
                'verbose_name_plural': 'Treinamentos',
            },
        ),
        migrations.CreateModel(
            name='Avaliation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.FileField(upload_to='', verbose_name='frequencia')),
                ('survey', models.FileField(upload_to='', verbose_name='pesquisa')),
                ('avaliation', models.FileField(blank=True, null=True, upload_to='', verbose_name='avaliação')),
                ('grades', models.FileField(blank=True, null=True, upload_to='', verbose_name='notas')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='data de inclusão')),
                ('preparation_class', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='my_avaliation', to='core.PreparationClass', verbose_name='Treinamento')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
            },
        ),
    ]
