# Generated by Django 2.2 on 2019-05-13 00:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliation',
            name='created_by',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='incluido por'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classregister',
            name='attendeeds',
            field=models.ManyToManyField(blank=True, to='user.Employee', verbose_name='Participantes'),
        ),
        migrations.AddField(
            model_name='classregister',
            name='preparation_class',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='my_register', to='core.PreparationClass', verbose_name='Registro do treinamento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='association',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='my_locations', to='core.Association', verbose_name='Unidade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preparationclass',
            name='association',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='my_preparations_classes', to='core.Association', verbose_name='Unidade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preparationclass',
            name='coach',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='my_classes', to='user.Employee', verbose_name='Tutor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preparationclass',
            name='employees',
            field=models.ManyToManyField(blank=True, related_name='my_preparations_classes', to='user.Employee', verbose_name='funcionarios'),
        ),
        migrations.AddField(
            model_name='preparationclass',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Location', verbose_name='Local do treinamento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preparationclass',
            name='positions',
            field=models.ManyToManyField(blank=True, related_name='my_preparations_classes', to='user.Position', verbose_name='cargos'),
        ),
    ]
