# Generated by Django 2.2 on 2019-04-06 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='admin',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='association', to='user.Employee', verbose_name='Administrador'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preparationclass',
            name='association',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='my_preparations_classes', to='core.Association', verbose_name='Unidade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preparationclass',
            name='coach',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='my_classes', to='user.Employee', verbose_name='Tutor'),
            preserve_default=False,
        ),
    ]
