# Generated by Django 2.2 on 2019-06-09 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190526_0352'),
        ('core', '0002_auto_20190513_0030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendeeds', models.ManyToManyField(blank=True, to='user.Employee', verbose_name='Participantes')),
                ('preparation_class', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='my_grades', to='core.PreparationClass', verbose_name='Treinamento')),
            ],
        ),
    ]
