# Generated by Django 2.2 on 2019-04-06 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190405_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='admin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='my_association', to='user.Employee', verbose_name='Administrador'),
        ),
    ]
