# Generated by Django 2.2 on 2019-06-09 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190526_0352'),
        ('core', '0003_grades'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grades',
            name='attendeeds',
        ),
        migrations.RemoveField(
            model_name='grades',
            name='preparation_class',
        ),
        migrations.AddField(
            model_name='avaliation',
            name='digital_grades',
            field=models.ManyToManyField(to='core.Grades', verbose_name='notas'),
        ),
        migrations.AddField(
            model_name='grades',
            name='employee',
            field=models.OneToOneField(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='user.Employee', verbose_name='Participantes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grades',
            name='value',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=2, verbose_name='nota'),
        ),
        migrations.AlterField(
            model_name='avaliation',
            name='grades',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='arquivo das notas'),
        ),
    ]
