# Generated by Django 2.2 on 2019-04-07 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190406_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='preparationclass',
            name='description',
            field=models.TextField(default='...', max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preparationclass',
            name='frequency',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='preparationclass',
            name='title',
            field=models.CharField(default='Title', max_length=75, verbose_name='Título do treinamento'),
            preserve_default=False,
        ),
    ]
