# Generated by Django 2.2 on 2019-04-12 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190410_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preparationclass',
            name='duration',
            field=models.IntegerField(help_text='quantidade em minutos', verbose_name='Duração do treinamento'),
        ),
    ]
