# Generated by Django 2.2 on 2019-06-09 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190609_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliation',
            name='digital_grades',
        ),
        migrations.AddField(
            model_name='grades',
            name='avaliation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='my_grades', to='core.Avaliation', verbose_name='notas'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='avaliation',
            name='frequency',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='frequencia'),
        ),
        migrations.AlterField(
            model_name='avaliation',
            name='survey',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='pesquisa'),
        ),
    ]
