# Generated by Django 2.2 on 2019-04-12 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190411_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='preparationclass',
            name='time',
            field=models.TimeField(auto_now=True, verbose_name='Hora do treinamento'),
        ),
        migrations.AlterField(
            model_name='preparationclass',
            name='duration',
            field=models.IntegerField(help_text='Nota: quantidade inserida em minutos', verbose_name='Duração do treinamento'),
        ),
    ]
