# Generated by Django 2.2 on 2019-06-16 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190609_1911'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grades',
            options={'verbose_name': 'Nota', 'verbose_name_plural': 'Notas'},
        ),
        migrations.AlterField(
            model_name='grades',
            name='employee',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='user.Employee', verbose_name='Participante'),
        ),
        migrations.AlterField(
            model_name='grades',
            name='value',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=30, verbose_name='nota'),
        ),
    ]
