# Generated by Django 2.2 on 2019-04-13 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190411_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preparationclass',
            name='location',
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, verbose_name='Nome do Local')),
                ('address', models.CharField(max_length=100, verbose_name='Endereço')),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_locations', to='core.Association', verbose_name='Unidade')),
            ],
        ),
    ]
