# Generated by Django 2.2 on 2019-06-16 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190615_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grades',
            name='employee',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='user.Employee', verbose_name='Participante'),
        ),
    ]
