# Generated by Django 2.2 on 2019-04-13 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190413_0151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Local', 'verbose_name_plural': 'Locais'},
        ),
        migrations.AddField(
            model_name='preparationclass',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Location', verbose_name='Local do treinamento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='preparationclass',
            name='time',
            field=models.TimeField(verbose_name='Hora do treinamento'),
        ),
    ]
