# Generated by Django 2.2 on 2019-04-17 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20190411_2149'),
        ('core', '0007_auto_20190413_0159'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_class', models.TimeField(blank=True, null=True, verbose_name='Início do treinamento')),
                ('end_class', models.TimeField(blank=True, null=True, verbose_name='Termino do treinamento')),
                ('conclude', models.BooleanField(default=False, verbose_name='Registro Concluido')),
                ('attendeeds', models.ManyToManyField(blank=True, to='user.Employee', verbose_name='Participantes')),
                ('preparation_class', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.PreparationClass', verbose_name='Registro do treinamento')),
            ],
        ),
    ]
