# Generated by Django 2.2 on 2019-04-24 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_classregister'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classregister',
            options={'verbose_name': 'Registro de Treino', 'verbose_name_plural': 'Registros de Treino'},
        ),
        migrations.CreateModel(
            name='Avaliation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.FileField(upload_to='')),
                ('survey', models.FileField(upload_to='')),
                ('avaliation', models.FileField(upload_to='')),
                ('grades', models.FileField(upload_to='')),
                ('preparation_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.PreparationClass', verbose_name='Treinamento')),
            ],
        ),
    ]
