# Generated by Django 2.2 on 2019-04-25 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190424_2233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avaliation',
            options={'verbose_name': 'Avaliação', 'verbose_name_plural': 'Avaliações'},
        ),
        migrations.AlterField(
            model_name='avaliation',
            name='avaliation',
            field=models.FileField(upload_to='', verbose_name='avaliação'),
        ),
        migrations.AlterField(
            model_name='avaliation',
            name='frequency',
            field=models.FileField(upload_to='', verbose_name='frequencia'),
        ),
        migrations.AlterField(
            model_name='avaliation',
            name='grades',
            field=models.FileField(upload_to='', verbose_name='notas'),
        ),
        migrations.AlterField(
            model_name='avaliation',
            name='preparation_class',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='my_avaliation', to='core.PreparationClass', verbose_name='Treinamento'),
        ),
        migrations.AlterField(
            model_name='avaliation',
            name='survey',
            field=models.FileField(upload_to='', verbose_name='pesquisa'),
        ),
    ]
