# Generated by Django 2.2 on 2019-04-25 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20190425_2156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avaliation',
            old_name='preparation_class',
            new_name='classes',
        ),
    ]
