# Generated by Django 2.2 on 2019-04-25 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20190425_2158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avaliation',
            old_name='classes',
            new_name='preparation_class',
        ),
    ]
