# Generated by Django 2.2 on 2019-05-05 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20190425_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classregister',
            name='preparation_class',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='my_register', to='core.PreparationClass', verbose_name='Registro do treinamento'),
        ),
    ]
