# Generated by Django 2.2 on 2019-05-05 18:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20190505_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='classregister',
            name='date',
            field=models.DateField(default=datetime.date(2019, 5, 5), verbose_name='Dia do registro'),
            preserve_default=False,
        ),
    ]
