# Generated by Django 2.2 on 2019-05-05 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_classregister_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classregister',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Dia do registro'),
        ),
    ]
