# Generated by Django 2.2 on 2019-05-11 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20190505_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliation',
            name='avaliation',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='avaliação'),
        ),
        migrations.AlterField(
            model_name='avaliation',
            name='grades',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='notas'),
        ),
    ]
