# Generated by Django 2.2 on 2019-05-12 01:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0016_auto_20190511_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliation',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='data de inclusão'),
        ),
        migrations.AddField(
            model_name='avaliation',
            name='created_by',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
