# Generated by Django 2.1 on 2019-03-23 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_preparationclass_coach'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='preparation_classes',
            field=models.ManyToManyField(related_name='Employees', to='core.PreparationClass'),
        ),
    ]
