# Generated by Django 2.2 on 2019-04-05 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190405_1040'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='preparation_classes',
            field=models.ManyToManyField(related_name='Employees', to='core.PreparationClass'),
        ),
    ]
