# Generated by Django 2.2 on 2019-04-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190409_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='can_create_preparationclass',
            field=models.BooleanField(default=False),
        ),
    ]
