# Generated by Django 2.2 on 2019-04-06 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190406_0050'),
        ('user', '0002_customuser_preparation_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='association',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='my_employees', to='core.Association', verbose_name='Unidade'),
            preserve_default=False,
        ),
    ]
