# Generated by Django 2.2 on 2019-04-12 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_position_can_create_preparationclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='can_create_preparationclass',
            field=models.BooleanField(default=False, verbose_name='Pode criar treinamentos'),
        ),
    ]
