# Generated by Django 2.2 on 2019-04-06 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190406_0050'),
        ('user', '0004_auto_20190406_0051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='association',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='preparation_classes',
        ),
        migrations.AddField(
            model_name='employee',
            name='association',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='my_employees', to='core.Association', verbose_name='Unidade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(default=1, max_length=150, verbose_name='Numero de Telefone'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='preparation_classes',
            field=models.ManyToManyField(related_name='employees', to='core.PreparationClass'),
        ),
    ]
