# Generated by Django 2.2 on 2019-04-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20190406_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='preparation_classes',
            field=models.ManyToManyField(blank=True, null=True, related_name='employees', to='core.PreparationClass', verbose_name='treinamentos'),
        ),
    ]
