# Generated by Django 2.2 on 2019-04-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20190408_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='preparation_classes',
            field=models.ManyToManyField(related_name='employees', to='core.PreparationClass', verbose_name='treinamentos'),
        ),
    ]
